[server]
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 10
maxMessageSize = 10

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#FFD700"
backgroundColor = "#1a1a2e"
secondaryBackgroundColor = "#16213e"
textColor = "#FFFFFF"
font = "sans serif"

[logger]
level = "INFO"